service: pull-eventbrite-events
provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "EventbriteEventsBucket"
            - "/*"
functions:
  produce:
    handler: handler.produce
    events:
      - schedule: rate(1 hour)
    environment:
      TZ: Europe/Belfast
      EVENTBRITE_API_TOKEN: ${ssm:eventbriteApiToken~true}
resources:
  Resources:
    EventbriteEventsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: eventbrite-events-bucket
